version: "3"

services:
  fastapi:
    image: app
    ports:
      - "8000:80"
    depends_on:
      pgdb:
        condition: service_healthy
    networks:
      - app-tier
  pgdb:
    image: postgis/postgis
    environment:
      POSTGRES_USER: jkaub
      POSTGRES_PASSWORD: jkaub
      POSTGRES_DB: stations
      PGDATA: /var/lib/postgresql/data/some_name/
    networks:
      - app-tier
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  redis:
    image: redis
    ports:
      - 6379
    networks:
      - app-tier
networks:
  app-tier:
    driver: bridge